### ISSUE TITLE
ReferenceError: assert is not defined

### ISSUE THREAD

**Issue by ghost** [visionmedia/expresso#76]
# Show installed modules

**$ npm ls installed**

npm info it worked if it ends with ok
npm info using npm@0.3.15
npm info using node@v0.4.2
async@0.1.0          installed   Higher-order functions and common patterns for asynchronous code  
async@0.1.8          active installed   Higher-order functions and common patterns for asynchronous code  
connect@1.0.3        installed   High performance middleware framework     framework web middleware connect rack
connect@1.0.4        installed   High performance middleware framework     framework web middleware connect rack
connect@1.0.6        active installed   High performance middleware framework     framework web middleware connect rack
emailjs@0.1.6        active installed   send text/html emails and attachments from node.js to any smtp server  
express@2.0.0beta2   installed   Sinatra inspired web development framework     framework sinatra web rest restful
express@2.0.0beta3   active installed   Sinatra inspired web development framework     framework sinatra web rest restful
expresso@0.7.3       active installed   TDD framework, light-weight, fast, CI-friendly  
formidable@0.9.11    active installed  
gently@0.8.0         active installed  
jade@0.8.4           installed   Jade template engine  
jade@0.8.5           active installed   Jade template engine  
mime@1.2.1           active installed   A comprehensive library for mime-type mapping     util mime
mongoose@1.1.3       installed   Mongoose MongoDB ORM     mongodb mongoose orm data datastore nosql
mongoose@1.1.4       active installed   Mongoose MongoDB ORM     mongodb mongoose orm data datastore nosql
npm@0.3.15           active installed   A package manager for node     package manager modules install package.json
qs@0.0.6             active installed   querystring parser
npm ok
# Show the content of test

*\* $ cat simple.test.js **

```
exports['testString#length'] = function() {
   assert.equal('abc'.length, 3);
}
```
# Run the test

**$ expresso simple.test.js**

```
simple.test.js testString#length: ReferenceError: assert is not defined
at /private/tmp/simple.test.js:2:3
at next (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:778:25)
at runSuite (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:796:6)
at check (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:703:16)
at runFile (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:707:10)
at Array.forEach (native)
at runFiles (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:684:13)
at run (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:653:5)
at Object.<anonymous> (/opt/local/lib/node/.npm/expresso/0.7.3/package/bin/expresso:864:13)
at Module._compile (module.js:383:26)


Failures: 1
```

**Comment by nickopaijo** [comment]
`import assert from 'node:assert'`

e.g. for module:
```
import test from 'node:test'
import assert from 'node:assert'
test('synchronous passing test', (t) => {
    // This test passes because it does not throw an exception.
    assert.strictEqual(1, 1);
});
```
